name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FOUNDER_TOKEN: ${{ secrets.FOUNDER_TOKEN }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      TRACE_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install -r requirements.txt mypy ruff
      - name: Validate secrets
        run: python3.11 scripts/validate_secrets.py
      - name: Lint
        run: ruff check .
      - name: Type check
        run: mypy --strict .
      - name: Run tests
        run: pytest -v
      - name: Metrics endpoint
        run: |
          python3.11 -m core.metrics --port 8001 &
          PID=$!
          sleep 2
          curl -f http://localhost:8001/metrics
          kill $PID
      - name: Fork simulation cross_rollup_superbot
        run: bash scripts/simulate_fork.sh --strategy=cross_rollup_superbot
      - name: Fork simulation l3_app_rollup_mev
        run: bash scripts/simulate_fork.sh --strategy=l3_app_rollup_mev
      - name: Fork simulation l3_sequencer_mev
        run: bash scripts/simulate_fork.sh --strategy=l3_sequencer_mev
      - name: Fork simulation nft_liquidation
        run: bash scripts/simulate_fork.sh --strategy=nft_liquidation
      - name: Fork simulation rwa_settlement
        run: bash scripts/simulate_fork.sh --strategy=rwa_settlement
      - name: DRP dry run
        run: bash scripts/export_state.sh --dry-run
      - name: Project audit export
        run: bash scripts/export_project_state.sh --dry-run
      - name: Offline audit
        run: python3.11 ai/audit_agent.py --mode=offline --logs logs/cross_rollup_superbot.json
      - name: Chaos drill
        run: python3.11 infra/sim_harness/chaos_drill.py
      - name: Tag canary
        run: |
          TAG="canary-${{ github.sha }}-$(date +%Y%m%d)"
          git tag "$TAG"
      - name: Canary tests
        run: |
          ruff check .
          mypy --strict .
          pytest -v
          bash scripts/simulate_fork.sh --strategy=cross_rollup_superbot
          bash scripts/simulate_fork.sh --strategy=l3_app_rollup_mev
          bash scripts/simulate_fork.sh --strategy=l3_sequencer_mev
          bash scripts/simulate_fork.sh --strategy=nft_liquidation
          bash scripts/simulate_fork.sh --strategy=rwa_settlement
          bash scripts/export_state.sh --dry-run
          python3.11 ai/audit_agent.py --mode=offline --logs logs/cross_rollup_superbot.json
      - name: Check gates
        run: python3.11 agents/check_gates.py
      - name: Promote
        if: env.FOUNDER_TOKEN != ''
        run: echo "Founder approval received. Ready for production."
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ env.TRACE_ID }}
          path: logs/
