name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FOUNDER_TOKEN: ${{ secrets.FOUNDER_TOKEN }}
      TRACE_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install -r requirements.txt mypy ruff
      - name: Lint
        run: ruff check .
      - name: Type check
        run: mypy --strict .
      - name: Run tests
        run: pytest -v
      - name: Fork simulation
        run: bash scripts/simulate_fork.sh --target=strategies/cross_domain_arb
      - name: DRP dry run
        run: bash scripts/export_state.sh --dry-run
      - name: Offline audit
        run: python3.11 ai/audit_agent.py --mode=offline --logs logs/cross_domain_arb.json
      - name: Chaos drill
        run: python3.11 infra/sim_harness/chaos_drill.py
      - name: Tag canary
        run: |
          TAG="canary-${{ github.sha }}-$(date +%Y%m%d)"
          git tag "$TAG"
      - name: Canary tests
        run: |
          ruff check .
          mypy --strict .
          pytest -v
          bash scripts/simulate_fork.sh --target=strategies/cross_domain_arb
          bash scripts/export_state.sh --dry-run
          python3.11 ai/audit_agent.py --mode=offline --logs logs/cross_domain_arb.json
      - name: Check gates
        run: python3.11 agents/check_gates.py
      - name: Promote
        if: env.FOUNDER_TOKEN != ''
        run: echo "Founder approval received. Ready for production."
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ env.TRACE_ID }}
          path: logs/
